insert into suggestion (Name, suggestName, message) values ('''', '¸˛Ç◊ı˜Â¯˘¿', 'dculpen0@shutterfly.com');
insert into suggestion (Name, suggestName, message) values ('0/0', '!@#$%^&*()', 'mgiacoppo1@mtv.com');
insert into suggestion (Name, suggestName, message) values ('␢', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'tharpur2@bloglovin.com');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', '-1E02', 'felger3@cbsnews.com');
insert into suggestion (Name, suggestName, message) values ('''"''', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'mcampion4@bing.com');
insert into suggestion (Name, suggestName, message) values ('`⁄€‹›ﬁﬂ‡°·‚—±', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'cglasser5@chicagotribune.com');
insert into suggestion (Name, suggestName, message) values ('`⁄€‹›ﬁﬂ‡°·‚—±', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 'fgilders6@un.org');
insert into suggestion (Name, suggestName, message) values ('１２３', 'Œ„´‰ˇÁ¨ˆØ∏”’', 'dvandijk7@macromedia.com');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', 'Œ„´‰ˇÁ¨ˆØ∏”’', 'ollywarch8@bluehost.com');
insert into suggestion (Name, suggestName, message) values ('｀ｨ(´∀｀∩', '/dev/null; touch /tmp/blns.fail ; echo', 'mpears9@t-online.de');
insert into suggestion (Name, suggestName, message) values ('1/2', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 'cbanaszczyka@si.edu');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', '/dev/null; touch /tmp/blns.fail ; echo', 'skinworthyb@vk.com');
insert into suggestion (Name, suggestName, message) values ('00˙Ɩ$-', '''"''', 'ttabbc@pen.io');
insert into suggestion (Name, suggestName, message) values ('1.00', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'kbenedicted@bloomberg.com');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'cbernardeaue@photobucket.com');
insert into suggestion (Name, suggestName, message) values ('̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', '‫test‫', 'lkubalekf@whitehouse.gov');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'bgreenacreg@geocities.com');
insert into suggestion (Name, suggestName, message) values ('''', '｀ｨ(´∀｀∩', 'eposseh@hud.gov');
insert into suggestion (Name, suggestName, message) values ('1E2', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'ddobbisoni@google.pl');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/passwd%00', '0.00', 'aforcerj@cocolog-nifty.com');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '-1/2', 'tsomersetk@dyndns.org');
insert into suggestion (Name, suggestName, message) values ('❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 'test', 'gscarlonl@examiner.com');
insert into suggestion (Name, suggestName, message) values ('ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', '・(￣∀￣)・:*:', 'jlewrym@tinyurl.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '¸˛Ç◊ı˜Â¯˘¿', 'kgarwilln@bbc.co.uk');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '-1E2', 'jberreyo@boston.com');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'rlippettp@indiegogo.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', 'null', 'dpeetersq@nhs.uk');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '␢', 'eturpinr@netvibes.com');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '1', 'ltillys@sourceforge.net');
insert into suggestion (Name, suggestName, message) values ('(｡◕ ∀ ◕｡)', 'test', 'fdeekt@nsw.gov.au');
insert into suggestion (Name, suggestName, message) values ('00˙Ɩ$-', '｀ｨ(´∀｀∩', 'fleyzellu@jalbum.net');
insert into suggestion (Name, suggestName, message) values ('null', '1', 'asherav@usatoday.com');
insert into suggestion (Name, suggestName, message) values ('1;DROP TABLE users', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'hmckiernanw@arizona.edu');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '-1E2', 'cmakeyx@edublogs.org');
insert into suggestion (Name, suggestName, message) values ('<img src=x onerror=alert(''hi'') />', '../../../../../../../../../../../etc/hosts', 'lwhiskerdy@google.es');
insert into suggestion (Name, suggestName, message) values ('部落格', '👩🏽', 'cfogelz@google.com.hk');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'null', 'djerschke10@google.com.br');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '␢', 'gforder11@amazon.com');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '␣', 'dpolino12@examiner.com');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'jkingescot13@hhs.gov');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '$1.00', 'elarvor14@bloglovin.com');
insert into suggestion (Name, suggestName, message) values ('1/2', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 'hhumberston15@nba.com');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'pdancey16@quantcast.com');
insert into suggestion (Name, suggestName, message) values ('␣', '¡™£¢∞§¶•ªº–≠', 'sneath17@youtu.be');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'chousegoe18@livejournal.com');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'ccrate19@blinklist.com');
insert into suggestion (Name, suggestName, message) values ('｀ｨ(´∀｀∩', 'הָיְתָהtestالصفحات التّحول', 'bparmiter1a@shop-pro.jp');
insert into suggestion (Name, suggestName, message) values ('｀ｨ(´∀｀∩', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'stodarello1b@wikimedia.org');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '₀₁₂', 'asoppitt1c@creativecommons.org');
insert into suggestion (Name, suggestName, message) values ('0.00', 'åß∂ƒ©˙∆˚¬…æ', 'amacanespie1d@wix.com');
insert into suggestion (Name, suggestName, message) values ('__ﾛ(,_,*)', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 'mcummins1e@craigslist.org');
insert into suggestion (Name, suggestName, message) values ('-1E02', '!@#$%^&*()', 'propp1f@indiatimes.com');
insert into suggestion (Name, suggestName, message) values ('""', '../../../../../../../../../../../etc/hosts', 'fpumphreys1g@umn.edu');
insert into suggestion (Name, suggestName, message) values ('1/0', '１２３', 'cmistry1h@ovh.net');
insert into suggestion (Name, suggestName, message) values ('﻿', '<>?:"{}|_+', 'ehassent1i@wordpress.org');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'lveld1j@360.cn');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 'elarder1k@yale.edu');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '사회과학원 어학연구소', 'aallain1l@mozilla.com');
insert into suggestion (Name, suggestName, message) values ('1''; DROP TABLE users--', 'œ∑´®†¥¨ˆøπ“‘', 'hhobben1m@sakura.ne.jp');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', '1', 'dmacrury1n@newsvine.com');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'obiss1o@so-net.ne.jp');
insert into suggestion (Name, suggestName, message) values ('␡', '・(￣∀￣)・:*:', 'veicheler1p@slideshare.net');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'bweller1q@ow.ly');
insert into suggestion (Name, suggestName, message) values ('1;DROP TABLE users', '社會科學院語學研究所', 'akehoe1r@taobao.com');
insert into suggestion (Name, suggestName, message) values ('Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', '1E2', 'cpim1s@intel.com');
insert into suggestion (Name, suggestName, message) values ('👩🏽', 'NIL', 'mbohlin1t@reverbnation.com');
insert into suggestion (Name, suggestName, message) values ('❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'ntrewartha1u@msu.edu');
insert into suggestion (Name, suggestName, message) values ('1E2', '"', 'rmurrish1v@google.de');
insert into suggestion (Name, suggestName, message) values ('١٢٣', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'lwiddison1w@webeden.co.uk');
insert into suggestion (Name, suggestName, message) values ('1', '‫test‫', 'ltethcote1x@thetimes.co.uk');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'mmartinec1y@sciencedirect.com');
insert into suggestion (Name, suggestName, message) values ('0/0', '/dev/null; touch /tmp/blns.fail ; echo', 'tbleackly1z@blog.com');
insert into suggestion (Name, suggestName, message) values ('-$1.00', 'הָיְתָהtestالصفحات التّحول', 'komahoney20@msu.edu');
insert into suggestion (Name, suggestName, message) values ('-1/2', null, 'bnovic21@wikipedia.org');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 'mvasyutkin22@imgur.com');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', '¸˛Ç◊ı˜Â¯˘¿', 'rkerswell23@google.com.br');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', '__ﾛ(,_,*)', 'mbutt24@dyndns.org');
insert into suggestion (Name, suggestName, message) values ('-$1.00', '-$1.00', 'cschaumaker25@cdc.gov');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', '‪‪test‪', 'cavrahm26@blinklist.com');
insert into suggestion (Name, suggestName, message) values ('<script>alert(''hi'')</script>', '"', 'keady27@sciencedaily.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', '/dev/null; touch /tmp/blns.fail ; echo', 'hcleary28@msu.edu');
insert into suggestion (Name, suggestName, message) values ('null', 'åß∂ƒ©˙∆˚¬…æ', 'hguihen29@nasa.gov');
insert into suggestion (Name, suggestName, message) values ('␢', '''''', 'chick2a@squarespace.com');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'mgoodboddy2b@upenn.edu');
insert into suggestion (Name, suggestName, message) values (' ', '1', 'acalliss2c@tamu.edu');
insert into suggestion (Name, suggestName, message) values ('"''"''"''''''''"', '''', 'dgirke2d@sohu.com');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '1E+02', 'gmcadam2e@ted.com');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', '｀ｨ(´∀｀∩', 'pfarryn2f@instagram.com');
insert into suggestion (Name, suggestName, message) values ('(｡◕ ∀ ◕｡)', '__ﾛ(,_,*)', 'jmcskeagan2g@wikimedia.org');
insert into suggestion (Name, suggestName, message) values ('˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'ctharme2h@hostgator.com');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', '-1E+02', 'ghowson2i@xing.com');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'fclinnick2j@hexun.com');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', 'test', 'gnortheast2k@wiley.com');
insert into suggestion (Name, suggestName, message) values ('😍', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 'tmaccourt2l@webnode.com');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '🐵 🙈 🙉 🙊', 'ewarcop2m@mashable.com');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', '-1E02', 'swhittington2n@twitter.com');
insert into suggestion (Name, suggestName, message) values ('̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 'cmacadam2o@pagesperso-orange.fr');
insert into suggestion (Name, suggestName, message) values ('¡™£¢∞§¶•ªº–≠', 'NIL', 'llangdon2p@studiopress.com');
insert into suggestion (Name, suggestName, message) values ('"''"''"''''''''"', '1E02', 'sbutterly2q@bbc.co.uk');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'wbough2r@virginia.edu');
insert into suggestion (Name, suggestName, message) values ('̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', '﻿', 'bbradly2s@typepad.com');
insert into suggestion (Name, suggestName, message) values ('-1', 'œ∑´®†¥¨ˆøπ“‘', 'eubsdell2t@multiply.com');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '¸˛Ç◊ı˜Â¯˘¿', 'swanderschek2u@github.com');
insert into suggestion (Name, suggestName, message) values ('¡™£¢∞§¶•ªº–≠', '''"''', 'lhiscoe2v@ocn.ne.jp');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', 'åß∂ƒ©˙∆˚¬…æ', 'sgritsaev2w@parallels.com');
insert into suggestion (Name, suggestName, message) values ('␢', '<>?:"{}|_+', 'hpeel2x@seattletimes.com');
insert into suggestion (Name, suggestName, message) values ('1E02', '1/2', 'lvaz2y@archive.org');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', '<svg><script>0<1>alert(''XSS'')</script>', 'sfoskin2z@yellowbook.com');
insert into suggestion (Name, suggestName, message) values ('1', '"''''''''"''"', 'llightfoot30@odnoklassniki.ru');
insert into suggestion (Name, suggestName, message) values ('😍', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'cgoldwater31@sbwire.com');
insert into suggestion (Name, suggestName, message) values ('"', '<script>alert(''hi'')</script>', 'bsahnow32@ocn.ne.jp');
insert into suggestion (Name, suggestName, message) values ('-1', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'rleeb33@unesco.org');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'gbelitz34@businessweek.com');
insert into suggestion (Name, suggestName, message) values ('() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', '​', 'wdeighan35@parallels.com');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', '👩🏽', 'asimkiss36@gizmodo.com');
insert into suggestion (Name, suggestName, message) values ('(╯°□°）╯︵ ┻━┻)  ', '¡™£¢∞§¶•ªº–≠', 'ccolclough37@independent.co.uk');
insert into suggestion (Name, suggestName, message) values ('울란바토르', 'Œ„´‰ˇÁ¨ˆØ∏”’', 'sion38@tripadvisor.com');
insert into suggestion (Name, suggestName, message) values ('0/0', '🐵 🙈 🙉 🙊', 'scoey39@apple.com');
insert into suggestion (Name, suggestName, message) values ('""', '1/2', 'zdumphrey3a@cpanel.net');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '(╯°□°）╯︵ ┻━┻)  ', 'amarriot3b@vistaprint.com');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', '₀₁₂', 'dcocher3c@youku.com');
insert into suggestion (Name, suggestName, message) values ('🐵 🙈 🙉 🙊', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'oflecknoe3d@plala.or.jp');
insert into suggestion (Name, suggestName, message) values (' ', '١٢٣', 'hmaine3e@opera.com');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'dhansell3f@1und1.de');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', 'test⁠test‫', 'jhandrek3g@aol.com');
insert into suggestion (Name, suggestName, message) values ('１２３', '(｡◕ ∀ ◕｡)', 'gfass3h@engadget.com');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '1', 'sohartnett3i@last.fm');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '-1E+02', 'muman3j@posterous.com');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 'bboyda3k@whitehouse.gov');
insert into suggestion (Name, suggestName, message) values ('() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', '﻿', 'gastridge3l@eepurl.com');
insert into suggestion (Name, suggestName, message) values ('ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', '👩🏽', 'ccastiello3m@shutterfly.com');
insert into suggestion (Name, suggestName, message) values ('<script>alert(''hi'')</script>', 'test⁠test‫', 'amcclinton3n@disqus.com');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '・(￣∀￣)・:*:', 'rodcroft3o@eepurl.com');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', '👩🏽', 'wwavish3p@ameblo.jp');
insert into suggestion (Name, suggestName, message) values ('-1/2', '社會科學院語學研究所', 'kcudbird3q@nasa.gov');
insert into suggestion (Name, suggestName, message) values ('👩🏽', '␡', 'fbeatson3r@exblog.jp');
insert into suggestion (Name, suggestName, message) values ('nil', '1', 'mmildenhall3s@psu.edu');
insert into suggestion (Name, suggestName, message) values ('👩🏽', '-1E02', 'dlickorish3t@umn.edu');
insert into suggestion (Name, suggestName, message) values ('"', '"''"''"''''''''"', 'ischade3u@state.gov');
insert into suggestion (Name, suggestName, message) values ('울란바토르', '<script>alert(''hi'')</script>', 'jdillingham3v@networksolutions.com');
insert into suggestion (Name, suggestName, message) values (' ', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'mkenforth3w@altervista.org');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '`⁄€‹›ﬁﬂ‡°·‚—±', 'sduggleby3x@omniture.com');
insert into suggestion (Name, suggestName, message) values ('NULL', '⁰⁴⁵₀₁₂', 'chagland3y@fda.gov');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'mdanet3z@drupal.org');
insert into suggestion (Name, suggestName, message) values ('<svg><script>0<1>alert(''XSS'')</script>', '<>?:"{}|_+', 'jrowbottam40@zdnet.com');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '₀₁₂', 'hspenley41@imageshack.us');
insert into suggestion (Name, suggestName, message) values ('"''"''"''''''''"', '1E2', 'aitzhayek42@icio.us');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', '1E2', 'ktowers43@twitter.com');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 'csydes44@cdbaby.com');
insert into suggestion (Name, suggestName, message) values ('-1.00', null, 'lvedstra45@businesswire.com');
insert into suggestion (Name, suggestName, message) values ('ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', '👩🏽', 'rgookey46@ehow.com');
insert into suggestion (Name, suggestName, message) values ('１２３', 'Ω≈ç√∫˜µ≤≥÷', 'dleinweber47@stumbleupon.com');
insert into suggestion (Name, suggestName, message) values ('-1E02', 'Ω≈ç√∫˜µ≤≥÷', 'belis48@shareasale.com');
insert into suggestion (Name, suggestName, message) values ('0.00', '社會科學院語學研究所', 'dstable49@yale.edu');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', '⁰⁴⁵', 'carnau4a@dagondesign.com');
insert into suggestion (Name, suggestName, message) values ('‫test‫', '-1', 'jduns4b@berkeley.edu');
insert into suggestion (Name, suggestName, message) values ('₀₁₂', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'aderechter4c@vk.com');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '部落格', 'alorans4d@hatena.ne.jp');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', 'הָיְתָהtestالصفحات التّحول', 'blob4e@macromedia.com');
insert into suggestion (Name, suggestName, message) values ('⁰⁴⁵', '-1E2', 'gbydaway4f@examiner.com');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '‪‪test‪', 'athorn4g@flickr.com');
insert into suggestion (Name, suggestName, message) values ('👩🏽', '''', 'awheowall4h@bizjournals.com');
insert into suggestion (Name, suggestName, message) values ('NULL', '␣', 'bpalfree4i@globo.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'lhellewell4j@alibaba.com');
insert into suggestion (Name, suggestName, message) values ('␡', 'NIL', 'olammenga4k@zdnet.com');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '<script>alert(''hi'')</script>', 'qbugdall4l@uol.com.br');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'gsawle4m@cyberchimps.com');
insert into suggestion (Name, suggestName, message) values ('NIL', 'パーティーへ行かないか', 'jmaccafferky4n@unicef.org');
insert into suggestion (Name, suggestName, message) values ('᠎', '0/0', 'mirving4o@simplemachines.org');
insert into suggestion (Name, suggestName, message) values ('1E02', '"''"''"''''''''"', 'bsamwaye4p@g.co');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'mpenlington4q@rambler.ru');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '!@#$%^&*()', 'pmitchenson4r@joomla.org');
insert into suggestion (Name, suggestName, message) values ('Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', '"''''''''"''"', 'kcharville4s@globo.com');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '␡', 'chodge4t@flickr.com');
insert into suggestion (Name, suggestName, message) values ('　', '(｡◕ ∀ ◕｡)', 'ekillwick4u@i2i.jp');
insert into suggestion (Name, suggestName, message) values ('NULL', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'ffranceschelli4v@mayoclinic.com');
insert into suggestion (Name, suggestName, message) values ('ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', '١٢٣', 'dhowsley4w@reverbnation.com');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'prottenbury4x@blogs.com');
insert into suggestion (Name, suggestName, message) values ('🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', '__ﾛ(,_,*)', 'bmault4y@reference.com');
insert into suggestion (Name, suggestName, message) values ('1''; DROP TABLE users--', 'NULL', 'wmcritchie4z@miibeian.gov.cn');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', '../../../../../../../../../../../etc/passwd%00', 'bchadburn50@booking.com');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', '1''; DROP TABLE users--', 'hkirwan51@nydailynews.com');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 'rdevitt52@eventbrite.com');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', '0.00', 'claydon53@gnu.org');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', '1.00', 'nleakner54@loc.gov');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', 'Œ„´‰ˇÁ¨ˆØ∏”’', 'gdedon55@hao123.com');
insert into suggestion (Name, suggestName, message) values ('''"''', '<script>alert(''hi'')</script>', 'tbolens56@xinhuanet.com');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', 'null', 'kshoard57@stumbleupon.com');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '1E02', 'bmart58@upenn.edu');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', '🐵 🙈 🙉 🙊', 'ndawley59@vkontakte.ru');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '・(￣∀￣)・:*:', 'mashbey5a@rambler.ru');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/passwd%00', 'הָיְתָהtestالصفحات التّحول', 'rguilleton5b@sohu.com');
insert into suggestion (Name, suggestName, message) values ('‪‪test‪', '１２３', 'tlibbis5c@examiner.com');
insert into suggestion (Name, suggestName, message) values ('1;DROP TABLE users', '1/0', 'gbrave5d@youtu.be');
insert into suggestion (Name, suggestName, message) values ('˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'null', 'lsalvadori5e@yahoo.co.jp');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', '(｡◕ ∀ ◕｡)', 'lkike5f@walmart.com');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 'œ∑´®†¥¨ˆøπ“‘', 'lromaynes5g@wired.com');
insert into suggestion (Name, suggestName, message) values (',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'test⁠test‫', 'iwimbush5h@friendfeed.com');
insert into suggestion (Name, suggestName, message) values ('‫test‫', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'kspiby5i@google.co.jp');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', 'パーティーへ行かないか', 'tbottomer5j@washingtonpost.com');
insert into suggestion (Name, suggestName, message) values ('"', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'mkeir5k@cbslocal.com');
insert into suggestion (Name, suggestName, message) values ('‪‪test‪', '-1/2', 'gbignal5l@cisco.com');
insert into suggestion (Name, suggestName, message) values ('NULL', '-1/2', 'astatter5m@reference.com');
insert into suggestion (Name, suggestName, message) values ('𠜎𠜱𠝹𠱓𠱸𠲖𠳏', '""', 'kmoat5n@yale.edu');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', '-1E+02', 'cpiggford5o@trellian.com');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', '﻿', 'eokelleher5p@shop-pro.jp');
insert into suggestion (Name, suggestName, message) values ('0/0', '1E+02', 'bcasserly5q@time.com');
insert into suggestion (Name, suggestName, message) values ('﻿', '-1E+02', 'rgregoli5r@umich.edu');
insert into suggestion (Name, suggestName, message) values ('␢', '　', 'pcapelen5s@sakura.ne.jp');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '(╯°□°）╯︵ ┻━┻)  ', 'jorpyne5t@reference.com');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '1''; DROP TABLE users--', 'tbadham5u@sina.com.cn');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'ndyson5v@free.fr');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'kgirodin5w@zimbio.com');
insert into suggestion (Name, suggestName, message) values ('울란바토르', '''', 'acamoletto5x@altervista.org');
insert into suggestion (Name, suggestName, message) values ('⁰⁴⁵', ',./;''[]\-=', 'cplaskitt5y@biglobe.ne.jp');
insert into suggestion (Name, suggestName, message) values ('❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', '👩🏽', 'eflaunders5z@ifeng.com');
insert into suggestion (Name, suggestName, message) values ('1/0', '1;DROP TABLE users', 'dliversedge60@miibeian.gov.cn');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '¸˛Ç◊ı˜Â¯˘¿', 'alansberry61@opensource.org');
insert into suggestion (Name, suggestName, message) values ('(｡◕ ∀ ◕｡)', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'mclapshaw62@twitter.com');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'marnaldo63@github.io');
insert into suggestion (Name, suggestName, message) values ('˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', '$1.00', 'eschultz64@blogs.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/passwd%00', 'パーティーへ行かないか', 'anelles65@artisteer.com');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', 'NIL', 'fweatherby66@deviantart.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', '-1E2', 'mgiacomoni67@google.cn');
insert into suggestion (Name, suggestName, message) values ('1/2', '"''"''"''''''''"', 'bpogosian68@sphinn.com');
insert into suggestion (Name, suggestName, message) values ('''', 'test', 'ecrinion69@google.fr');
insert into suggestion (Name, suggestName, message) values ('""', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'cbabb6a@weibo.com');
insert into suggestion (Name, suggestName, message) values ('-1.00', '₀₁₂', 'gkivlehan6b@latimes.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '00˙Ɩ$-', 'dfiller6c@umich.edu');
insert into suggestion (Name, suggestName, message) values ('''', 'Œ„´‰ˇÁ¨ˆØ∏”’', 'ttorald6d@msn.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', 'הָיְתָהtestالصفحات التّحول', 'jblant6e@shareasale.com');
insert into suggestion (Name, suggestName, message) values ('𠜎𠜱𠝹𠱓𠱸𠲖𠳏', '/dev/null; touch /tmp/blns.fail ; echo', 'vwindrum6f@drupal.org');
insert into suggestion (Name, suggestName, message) values ('() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', '-1E02', 'dhannigane6g@jalbum.net');
insert into suggestion (Name, suggestName, message) values ('¡™£¢∞§¶•ªº–≠', '1;DROP TABLE users', 'byanin6h@fastcompany.com');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'ebuddock6i@reddit.com');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '../../../../../../../../../../../etc/passwd%00', 'chorley6j@linkedin.com');
insert into suggestion (Name, suggestName, message) values (null, 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'jgregolin6k@google.ru');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'rbrighouse6l@kickstarter.com');
insert into suggestion (Name, suggestName, message) values (',./;''[]\-=', '$1.00', 'cdukelow6m@is.gd');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'cridgwell6n@merriam-webster.com');
insert into suggestion (Name, suggestName, message) values ('🐵 🙈 🙉 🙊', '"''''''''"''"', 'jsaxon6o@sfgate.com');
insert into suggestion (Name, suggestName, message) values ('() { 0; }; touch /tmp/blns.shellshock1.fail;', '울란바토르', 'crolinson6p@dailymail.co.uk');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '-1', 'cferronier6q@amazon.com');
insert into suggestion (Name, suggestName, message) values ('''''', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'tdreus6r@berkeley.edu');
insert into suggestion (Name, suggestName, message) values ('😍', '😍', 'tdowsing6s@multiply.com');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'fraden6t@unblog.fr');
insert into suggestion (Name, suggestName, message) values ('˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', '$1.00', 'pgarden6u@msn.com');
insert into suggestion (Name, suggestName, message) values ('1E2', '"''''''''"''"', 'csanper6v@w3.org');
insert into suggestion (Name, suggestName, message) values ('הָיְתָהtestالصفحات التّحول', '!@#$%^&*()', 'lbambrough6w@joomla.org');
insert into suggestion (Name, suggestName, message) values ('0.00', '-1E+02', 'hdugdale6x@vkontakte.ru');
insert into suggestion (Name, suggestName, message) values ('''"''', '<script>alert(''hi'')</script>', 'cloughney6y@hibu.com');
insert into suggestion (Name, suggestName, message) values ('1.00', '1E02', 'sfenimore6z@newyorker.com');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', ',./;''[]\-=', 'cminchin70@google.cn');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', '-1/2', 'alilburne71@ibm.com');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '1/2', 'bmechan72@businesswire.com');
insert into suggestion (Name, suggestName, message) values ('<img src=x onerror=alert(''hi'') />', '｀ｨ(´∀｀∩', 'jochiltree73@cdc.gov');
insert into suggestion (Name, suggestName, message) values ('0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'acaris74@51.la');
insert into suggestion (Name, suggestName, message) values ('⁰⁴⁵', '1E2', 'acharlick75@cbslocal.com');
insert into suggestion (Name, suggestName, message) values ('　', '​', 'cwatkiss76@google.co.uk');
insert into suggestion (Name, suggestName, message) values ('0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', '(｡◕ ∀ ◕｡)', 'fmacaree77@wikia.com');
insert into suggestion (Name, suggestName, message) values ('和製漢語', 'test', 'rtreffrey78@kickstarter.com');
insert into suggestion (Name, suggestName, message) values ('😍', '''"''', 'mfoley79@hao123.com');
insert into suggestion (Name, suggestName, message) values ('<script>alert(''hi'')</script>', '1E2', 'bdewfall7a@nationalgeographic.com');
insert into suggestion (Name, suggestName, message) values ('''''', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 'waindrais7b@slideshare.net');
insert into suggestion (Name, suggestName, message) values ('''"''', '社會科學院語學研究所', 'bbrient7c@wired.com');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'yaisthorpe7d@typepad.com');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'pgates7e@cdbaby.com');
insert into suggestion (Name, suggestName, message) values (',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', '1E02', 'opresdee7f@pinterest.com');
insert into suggestion (Name, suggestName, message) values ('｀ｨ(´∀｀∩', '울란바토르', 'gbrierley7g@ucoz.ru');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', '‪‪test‪', 'kkerans7h@wikimedia.org');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', '1E02', 'bcordaroy7i@dropbox.com');
insert into suggestion (Name, suggestName, message) values ('部落格', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'ceshelby7j@nymag.com');
insert into suggestion (Name, suggestName, message) values ('''"''', '🐵 🙈 🙉 🙊', 'fmiranda7k@yolasite.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', '0/0', 'mdreossi7l@example.com');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', '`⁄€‹›ﬁﬂ‡°·‚—±', 'lgrizard7m@house.gov');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '00˙Ɩ$-', 'mbraid7n@businessweek.com');
insert into suggestion (Name, suggestName, message) values ('-1E+02', 'null', 'dcarswell7o@flickr.com');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', '<script>alert(''hi'')</script>', 'dbrundale7p@cisco.com');
insert into suggestion (Name, suggestName, message) values ('‫test‫', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'saarons7q@macromedia.com');
insert into suggestion (Name, suggestName, message) values ('‫test‫', '""', 'gmelvin7r@netscape.com');
insert into suggestion (Name, suggestName, message) values ('-1E2', '‪‪test‪', 'hwilkin7s@clickbank.net');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '１２３', 'avickarman7t@prweb.com');
insert into suggestion (Name, suggestName, message) values ('🐵 🙈 🙉 🙊', 'הָיְתָהtestالصفحات التّحول', 'omill7u@miibeian.gov.cn');
insert into suggestion (Name, suggestName, message) values ('​', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'rmerriman7v@google.pl');
insert into suggestion (Name, suggestName, message) values ('₀₁₂', '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', 'kpantling7w@bandcamp.com');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '1;DROP TABLE users', 'sminchell7x@msn.com');
insert into suggestion (Name, suggestName, message) values ('null', 'åß∂ƒ©˙∆˚¬…æ', 'hdykins7y@goo.ne.jp');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'mcundict7z@gmpg.org');
insert into suggestion (Name, suggestName, message) values ('❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'ldoding80@qq.com');
insert into suggestion (Name, suggestName, message) values ('-$1.00', 'test', 'shousam81@forbes.com');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 'dsmullen82@gnu.org');
insert into suggestion (Name, suggestName, message) values ('部落格', '⁰⁴⁵₀₁₂', 'mbirtonshaw83@forbes.com');
insert into suggestion (Name, suggestName, message) values (' ', '部落格', 'mmcbay84@tinyurl.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'lyesichev85@nyu.edu');
insert into suggestion (Name, suggestName, message) values ('-1', '田中さんにあげて下さい', 'clegge86@amazon.co.uk');
insert into suggestion (Name, suggestName, message) values ('0.00', '<>?:"{}|_+', 'dadamowicz87@unicef.org');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', ',./;''[]\-=', 'lhutchison88@google.de');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'wthieme89@hc360.com');
insert into suggestion (Name, suggestName, message) values ('0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', '0.00', 'eanton8a@wufoo.com');
insert into suggestion (Name, suggestName, message) values ('nil', '''''', 'sbartens8b@ftc.gov');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '和製漢語', 'jmarney8c@creativecommons.org');
insert into suggestion (Name, suggestName, message) values ('🐵 🙈 🙉 🙊', '사회과학원 어학연구소', 'spowles8d@wsj.com');
insert into suggestion (Name, suggestName, message) values ('$1.00', '''"''', 'lmcduffy8e@naver.com');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '(｡◕ ∀ ◕｡)', 'wlyle8f@xrea.com');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '‫test‫', 'lshropshire8g@slashdot.org');
insert into suggestion (Name, suggestName, message) values ('åß∂ƒ©˙∆˚¬…æ', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'emcdoual8h@icio.us');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', '‫test‫', 'rcratchley8i@google.it');
insert into suggestion (Name, suggestName, message) values ('Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', '₀₁₂', 'agonsalo8j@fema.gov');
insert into suggestion (Name, suggestName, message) values ('''"''', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'fmunning8k@army.mil');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'glintall8l@economist.com');
insert into suggestion (Name, suggestName, message) values ('-1', '1E02', 'ldorrell8m@opensource.org');
insert into suggestion (Name, suggestName, message) values ('''''', '¡™£¢∞§¶•ªº–≠', 'enund8n@goo.ne.jp');
insert into suggestion (Name, suggestName, message) values ('NIL', '₀₁₂', 'eportriss8o@pbs.org');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 'swrotham8p@php.net');
insert into suggestion (Name, suggestName, message) values ('<script>alert(''hi'')</script>', '1E2', 'krohlf8q@hexun.com');
insert into suggestion (Name, suggestName, message) values ('NIL', '1;DROP TABLE users', 'nballam8r@pen.io');
insert into suggestion (Name, suggestName, message) values ('̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', '''''', 'rofogarty8s@irs.gov');
insert into suggestion (Name, suggestName, message) values ('1''; DROP TABLE users--', '''"''', 'kbabonau8t@goodreads.com');
insert into suggestion (Name, suggestName, message) values ('"', '$1.00', 'bmartland8u@mtv.com');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', null, 'jkidby8v@mit.edu');
insert into suggestion (Name, suggestName, message) values ('0.00', '/dev/null; touch /tmp/blns.fail ; echo', 'cpund8w@histats.com');
insert into suggestion (Name, suggestName, message) values ('社會科學院語學研究所', '<>?:"{}|_+', 'dbrimacombe8x@rambler.ru');
insert into suggestion (Name, suggestName, message) values ('-1', '部落格', 'wcobley8y@artisteer.com');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '<>?:"{}|_+', 'emacanelley8z@harvard.edu');
insert into suggestion (Name, suggestName, message) values ('''''', 'œ∑´®†¥¨ˆøπ“‘', 'olinfield90@about.com');
insert into suggestion (Name, suggestName, message) values ('`⁄€‹›ﬁﬂ‡°·‚—±', null, 'nturpin91@ihg.com');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '''', 'emerriman92@miibeian.gov.cn');
insert into suggestion (Name, suggestName, message) values ('"', '../../../../../../../../../../../etc/hosts', 'twallas93@google.co.jp');
insert into suggestion (Name, suggestName, message) values ('᠎', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'gheminsley94@xinhuanet.com');
insert into suggestion (Name, suggestName, message) values ('᠎', '和製漢語', 'edrackford95@oracle.com');
insert into suggestion (Name, suggestName, message) values ('<img src=x onerror=alert(''hi'') />', 'NULL', 'tsadgrove96@unicef.org');
insert into suggestion (Name, suggestName, message) values ('(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', ',./;''[]\-=', 'gtrapp97@ow.ly');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'cdenisard98@google.co.jp');
insert into suggestion (Name, suggestName, message) values ('() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', '''', 'bpaniman99@yelp.com');
insert into suggestion (Name, suggestName, message) values ('₀₁₂', '00˙Ɩ$-', 'gmarklin9a@blog.com');
insert into suggestion (Name, suggestName, message) values (',./;''[]\-=', '部落格', 'mmcgourty9b@sina.com.cn');
insert into suggestion (Name, suggestName, message) values ('''"''', '$1.00', 'jsamuels9c@msn.com');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'cgiacopazzi9d@nationalgeographic.com');
insert into suggestion (Name, suggestName, message) values ('1/0', 'åß∂ƒ©˙∆˚¬…æ', 'fschuricke9e@webs.com');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', '⁰⁴⁵', 'sgoodlip9f@reddit.com');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '-1E02', 'udevonside9g@surveymonkey.com');
insert into suggestion (Name, suggestName, message) values ('999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', '1E+02', 'kbandey9h@pcworld.com');
insert into suggestion (Name, suggestName, message) values ('"', '​', 'hdaniaud9i@ning.com');
insert into suggestion (Name, suggestName, message) values ('1/0', '1E02', 'btame9j@archive.org');
insert into suggestion (Name, suggestName, message) values ('""', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'mcowgill9k@free.fr');
insert into suggestion (Name, suggestName, message) values ('1E2', '1.00', 'nmandy9l@columbia.edu');
insert into suggestion (Name, suggestName, message) values ('0/0', '␢', 'luccelli9m@exblog.jp');
insert into suggestion (Name, suggestName, message) values ('1''; DROP TABLE users--', '사회과학원 어학연구소', 'rrolance9n@i2i.jp');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', '1', 'vmcelhargy9o@ca.gov');
insert into suggestion (Name, suggestName, message) values ('1', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'nlapthorn9p@youtu.be');
insert into suggestion (Name, suggestName, message) values ('-1', 'åß∂ƒ©˙∆˚¬…æ', 'lskews9q@sitemeter.com');
insert into suggestion (Name, suggestName, message) values ('-1/2', '1E+02', 'hswadlen9r@wiley.com');
insert into suggestion (Name, suggestName, message) values ('和製漢語', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'jmunroe9s@cisco.com');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', ' ', 'anellis9t@ca.gov');
insert into suggestion (Name, suggestName, message) values ('₀₁₂', '1E2', 'cormond9u@irs.gov');
insert into suggestion (Name, suggestName, message) values ('åß∂ƒ©˙∆˚¬…æ', '-1/2', 'pmoorman9v@rambler.ru');
insert into suggestion (Name, suggestName, message) values ('̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'ktrouncer9w@who.int');
insert into suggestion (Name, suggestName, message) values ('1E+02', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'ucloney9x@twitter.com');
insert into suggestion (Name, suggestName, message) values ('NIL', '-1', 'gragborne9y@clickbank.net');
insert into suggestion (Name, suggestName, message) values ('Ω≈ç√∫˜µ≤≥÷', '-1E02', 'rgoldsbury9z@java.com');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '1E02', 'ndarcoa0@wikispaces.com');
insert into suggestion (Name, suggestName, message) values ('"', '👩🏽', 'vhatherleigha1@rediff.com');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '1E+02', 'cwitherspoona2@mediafire.com');
insert into suggestion (Name, suggestName, message) values ('"''"''"''''''''"', '"', 'mklampka3@xing.com');
insert into suggestion (Name, suggestName, message) values ('😍', '¸˛Ç◊ı˜Â¯˘¿', 'lluxtona4@usgs.gov');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', '(╯°□°）╯︵ ┻━┻)  ', 'ldonohoea5@howstuffworks.com');
insert into suggestion (Name, suggestName, message) values ('() { 0; }; touch /tmp/blns.shellshock1.fail;', 'NIL', 'tannotta6@cafepress.com');
insert into suggestion (Name, suggestName, message) values ('-1/2', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'wtamblinga7@gnu.org');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '(╯°□°）╯︵ ┻━┻)  ', 'ajeaysa8@home.pl');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'khargatea9@state.tx.us');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', '部落格', 'sgirardeyaa@smh.com.au');
insert into suggestion (Name, suggestName, message) values ('1.00', 'œ∑´®†¥¨ˆøπ“‘', 'lmoffatab@howstuffworks.com');
insert into suggestion (Name, suggestName, message) values ('-1', '１２３', 'fknivetonac@is.gd');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '<>?:"{}|_+', 'lseftonad@wikipedia.org');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '‪‪test‪', 'bskyppeae@go.com');
insert into suggestion (Name, suggestName, message) values (',./;''[]\-=', '1/2', 'jgiovanniniaf@cloudflare.com');
insert into suggestion (Name, suggestName, message) values ('"''''''''"''"', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'rvolonteag@t-online.de');
insert into suggestion (Name, suggestName, message) values ('和製漢語', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 'gmclennanah@live.com');
insert into suggestion (Name, suggestName, message) values ('__ﾛ(,_,*)', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'wburlandai@marriott.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'lemanulssonaj@cnn.com');
insert into suggestion (Name, suggestName, message) values ('1E+02', '-1E02', 'bpinneyak@home.pl');
insert into suggestion (Name, suggestName, message) values ('١٢٣', '''"''', 'earrowsmithal@blog.com');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', '"''''''''"''"', 'bskirvingam@google.co.jp');
insert into suggestion (Name, suggestName, message) values ('⁰⁴⁵', 'œ∑´®†¥¨ˆøπ“‘', 'clauxan@japanpost.jp');
insert into suggestion (Name, suggestName, message) values ('00˙Ɩ$-', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 'hvanderkruijsao@ovh.net');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'vlinkeap@go.com');
insert into suggestion (Name, suggestName, message) values ('1E2', '¸˛Ç◊ı˜Â¯˘¿', 'mfronczakaq@yandex.ru');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', null, 'jpuckringar@deviantart.com');
insert into suggestion (Name, suggestName, message) values ('ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', '﻿', 'fbertlinas@joomla.org');
insert into suggestion (Name, suggestName, message) values ('""', '1E2', 'rcalafateat@tinyurl.com');
insert into suggestion (Name, suggestName, message) values ('"', '‪‪test‪', 'kingsau@buzzfeed.com');
insert into suggestion (Name, suggestName, message) values ('1''; DROP TABLE users--', '<>?:"{}|_+', 'nsatterleeav@bandcamp.com');
insert into suggestion (Name, suggestName, message) values ('𠜎𠜱𠝹𠱓𠱸𠲖𠳏', '1/2', 'tocorrinaw@vimeo.com');
insert into suggestion (Name, suggestName, message) values ('1E02', '田中さんにあげて下さい', 'cgoldieax@ning.com');
insert into suggestion (Name, suggestName, message) values ('¸˛Ç◊ı˜Â¯˘¿', '‪‪test‪', 'eliberoay@exblog.jp');
insert into suggestion (Name, suggestName, message) values ('test', 'Ω≈ç√∫˜µ≤≥÷', 'wyakovitchaz@smh.com.au');
insert into suggestion (Name, suggestName, message) values ('˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥', '1E02', 'cmckinnab0@com.com');
insert into suggestion (Name, suggestName, message) values ('-1E2', ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', 'itippettsb1@hostgator.com');
insert into suggestion (Name, suggestName, message) values ('NULL', 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'astateb2@pcworld.com');
insert into suggestion (Name, suggestName, message) values ('<img src=x onerror=alert(''hi'') />', '1;DROP TABLE users', 'adeatheb3@elegantthemes.com');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '‫test‫', 'ipysonb4@sourceforge.net');
insert into suggestion (Name, suggestName, message) values ('1.00', '‪‪test‪', 'nenosb5@comcast.net');
insert into suggestion (Name, suggestName, message) values ('<svg><script>0<1>alert(''XSS'')</script>', 'nil', 'zstopperb6@vk.com');
insert into suggestion (Name, suggestName, message) values ('""', '社會科學院語學研究所', 'dotteeb7@blog.com');
insert into suggestion (Name, suggestName, message) values ('-1E02', '"''"''"''''''''"', 'smackowleb8@eepurl.com');
insert into suggestion (Name, suggestName, message) values ('̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', 'sdrewcliftonb9@fotki.com');
insert into suggestion (Name, suggestName, message) values ('(╯°□°）╯︵ ┻━┻)  ', 'null', 'amccrackenba@gov.uk');
insert into suggestion (Name, suggestName, message) values ('‫test‫', '🚾 🆒 🆓 🆕 🆖 🆗 🆙 🏧', 'bmattocksbb@senate.gov');
insert into suggestion (Name, suggestName, message) values ('Œ„´‰ˇÁ¨ˆØ∏”’', '1', 'atourbc@ted.com');
insert into suggestion (Name, suggestName, message) values ('''', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 'ljarrettebd@salon.com');
insert into suggestion (Name, suggestName, message) values ('ÅÍÎÏ˝ÓÔÒÚÆ☃', 'ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ', 'mmintoftbe@163.com');
insert into suggestion (Name, suggestName, message) values ('1E02', '../../../../../../../../../../../etc/hosts', 'esetterfieldbf@webmd.com');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', '<svg><script>0<1>alert(''XSS'')</script>', 'lastbg@usda.gov');
insert into suggestion (Name, suggestName, message) values (',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'ddunckleybh@weebly.com');
insert into suggestion (Name, suggestName, message) values ('｀ｨ(´∀｀∩', ' ', 'fpyrahbi@godaddy.com');
insert into suggestion (Name, suggestName, message) values ('₀₁₂', '"''"''"''''''''"', 'credierbj@miitbeian.gov.cn');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '`⁄€‹›ﬁﬂ‡°·‚—±', 'msaxonbk@hubpages.com');
insert into suggestion (Name, suggestName, message) values ('👩🏽', '⁰⁴⁵', 'ffischerbl@globo.com');
insert into suggestion (Name, suggestName, message) values ('⁦test⁧', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'vbrounfieldbm@telegraph.co.uk');
insert into suggestion (Name, suggestName, message) values ('NULL', 'Ω≈ç√∫˜µ≤≥÷', 'cbanvillebn@netscape.com');
insert into suggestion (Name, suggestName, message) values ('1/0', 'הָיְתָהtestالصفحات التّحول', 'btaylotbo@cnet.com');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '᠎', 'ereicherzbp@php.net');
insert into suggestion (Name, suggestName, message) values ('̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', '␣', 'llandrebq@livejournal.com');
insert into suggestion (Name, suggestName, message) values ('사회과학원 어학연구소', '00˙Ɩ$-', 'gprettyjohnsbr@constantcontact.com');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '../../../../../../../../../../../etc/passwd%00', 'lwoolandbs@baidu.com');
insert into suggestion (Name, suggestName, message) values ('test⁠test‫', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 'bmaddisonbt@wufoo.com');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '⁦test⁧', 'hpittambu@census.gov');
insert into suggestion (Name, suggestName, message) values ('__ﾛ(,_,*)', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 'tgleedbv@imageshack.us');
insert into suggestion (Name, suggestName, message) values ('-1E2', '​', 'gclewsbw@latimes.com');
insert into suggestion (Name, suggestName, message) values ('‪‪test‪', '᠎', 'ebonninbx@goo.gl');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '␣', 'cpottsby@gnu.org');
insert into suggestion (Name, suggestName, message) values ('‫test‫', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 'tjoseybz@ovh.net');
insert into suggestion (Name, suggestName, message) values ('-1E2', '␢', 'nleatherbarrowc0@java.com');
insert into suggestion (Name, suggestName, message) values ('(｡◕ ∀ ◕｡)', '00˙Ɩ$-', 'bcloggc1@amazon.co.jp');
insert into suggestion (Name, suggestName, message) values ('-1/2', '₀₁₂', 'zstrachanc2@barnesandnoble.com');
insert into suggestion (Name, suggestName, message) values ('-1', '¡™£¢∞§¶•ªº–≠', 'nstrikerc3@ocn.ne.jp');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', 'test', 'bfreelandc4@a8.net');
insert into suggestion (Name, suggestName, message) values ('‫test‫', '<svg><script>0<1>alert(''XSS'')</script>', 'agenneyc5@time.com');
insert into suggestion (Name, suggestName, message) values ('1E+02', '0/0', 'mtodorc6@japanpost.jp');
insert into suggestion (Name, suggestName, message) values ('1E2', '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999', 'bblackettc7@biglobe.ne.jp');
insert into suggestion (Name, suggestName, message) values ('-1/2', '""', 'hdoddridgec8@cornell.edu');
insert into suggestion (Name, suggestName, message) values ('''', '1''; DROP TABLE users--', 'afosterc9@angelfire.com');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', '''', 'wtwiddleca@census.gov');
insert into suggestion (Name, suggestName, message) values ('() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', '-1/2', 'dlannoncb@gov.uk');
insert into suggestion (Name, suggestName, message) values ('⁰⁴⁵', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 'llightbowncc@rambler.ru');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/passwd%00', '''''', 'alerohancd@columbia.edu');
insert into suggestion (Name, suggestName, message) values ('-1', '$1.00', 'lbrewettce@delicious.com');
insert into suggestion (Name, suggestName, message) values ('-1E+02', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 'ngrowcockcf@de.vu');
insert into suggestion (Name, suggestName, message) values ('1E02', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 'mwinchurchcg@bigcartel.com');
insert into suggestion (Name, suggestName, message) values ('・(￣∀￣)・:*:', '👩🏽', 'sivamych@cdbaby.com');
insert into suggestion (Name, suggestName, message) values ('""', '١٢٣', 'rnelliesci@pinterest.com');
insert into suggestion (Name, suggestName, message) values ('Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣', 'test⁠test‫', 'haaronscj@drupal.org');
insert into suggestion (Name, suggestName, message) values ('-1/2', null, 'mcowperthwaiteck@naver.com');
insert into suggestion (Name, suggestName, message) values ('בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', '🐵 🙈 🙉 🙊', 'mmaciascl@sourceforge.net');
insert into suggestion (Name, suggestName, message) values ('NULL', '-1/2', 'mrickettcm@devhub.com');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '""', 'fsanpercn@hp.com');
insert into suggestion (Name, suggestName, message) values (',./;''[]\-=', ',./;''[]\-=', 'wgatenbyco@google.pl');
insert into suggestion (Name, suggestName, message) values ('/dev/null; touch /tmp/blns.fail ; echo', '/dev/null; touch /tmp/blns.fail ; echo', 'mloynescp@marketwatch.com');
insert into suggestion (Name, suggestName, message) values ('ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', '1.00', 'dartuscq@nsw.gov.au');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', ',./;''[]\-=', 'pordishcr@google.ca');
insert into suggestion (Name, suggestName, message) values ('1/0', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'aseeleycs@si.edu');
insert into suggestion (Name, suggestName, message) values ('␢', '﻿', 'ematyuginct@arstechnica.com');
insert into suggestion (Name, suggestName, message) values ('🐵 🙈 🙉 🙊', '1.00', 'pbillboroughcu@vinaora.com');
insert into suggestion (Name, suggestName, message) values ('nil', 'nil', 'jsclatercv@abc.net.au');
insert into suggestion (Name, suggestName, message) values ('<img src=x onerror=alert(''hi'') />', '⁦test⁧', 'aswaitecw@nsw.gov.au');
insert into suggestion (Name, suggestName, message) values ('0/0', '0.00', 'smanioncx@simplemachines.org');
insert into suggestion (Name, suggestName, message) values ('0/0', '田中さんにあげて下さい', 'aconklincy@usgs.gov');
insert into suggestion (Name, suggestName, message) values ('0.00', '部落格', 'avanyushkincz@apple.com');
insert into suggestion (Name, suggestName, message) values ('-1', '1E02', 'wspunerd0@redcross.org');
insert into suggestion (Name, suggestName, message) values ('-1E02', 'test', 'gseefeldtd1@4shared.com');
insert into suggestion (Name, suggestName, message) values ('''''', '⁰⁴⁵₀₁₂', 'dmcdougalld2@wufoo.com');
insert into suggestion (Name, suggestName, message) values ('¡™£¢∞§¶•ªº–≠', '¸˛Ç◊ı˜Â¯˘¿', 'wfrydd3@yale.edu');
insert into suggestion (Name, suggestName, message) values ('𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'test⁠test‫', 'rhowgegod4@irs.gov');
insert into suggestion (Name, suggestName, message) values ('-1/2', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'eneadsd5@free.fr');
insert into suggestion (Name, suggestName, message) values ('田中さんにあげて下さい', '❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', 'dbolderstoned6@ameblo.jp');
insert into suggestion (Name, suggestName, message) values ('<script>alert(''hi'')</script>', '() { 0; }; touch /tmp/blns.shellshock1.fail;', 'ehallowsd7@reuters.com');
insert into suggestion (Name, suggestName, message) values ('❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙', '"''"''"''''''''"', 'dmogied8@drupal.org');
insert into suggestion (Name, suggestName, message) values ('␣', '00˙Ɩ$-', 'pmccorkindaled9@apple.com');
insert into suggestion (Name, suggestName, message) values ('œ∑´®†¥¨ˆøπ“‘', '''', 'pbegbieda@whitehouse.gov');
insert into suggestion (Name, suggestName, message) values ('👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', '사회과학원 어학연구소', 'hlessmaredb@abc.net.au');
insert into suggestion (Name, suggestName, message) values ('åß∂ƒ©˙∆˚¬…æ', '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }', 'krosbergdc@cnet.com');
insert into suggestion (Name, suggestName, message) values ('$1.00', '‪‪test‪', 'iknightondd@exblog.jp');
insert into suggestion (Name, suggestName, message) values ('1E02', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 'chillandde@t.co');
insert into suggestion (Name, suggestName, message) values ('`⁄€‹›ﬁﬂ‡°·‚—±', '١٢٣', 'schyuertondf@weibo.com');
insert into suggestion (Name, suggestName, message) values ('部落格', '¡™£¢∞§¶•ªº–≠', 'jnottondg@dailymotion.com');
insert into suggestion (Name, suggestName, message) values ('部落格', '-1E2', 'elesterdh@yahoo.co.jp');
insert into suggestion (Name, suggestName, message) values ('パーティーへ行かないか', '''', 'imerigotdi@tmall.com');
insert into suggestion (Name, suggestName, message) values ('-1E2', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 'elinsteaddj@diigo.com');
insert into suggestion (Name, suggestName, message) values ('␡', '<script>alert(''hi'')</script>', 'mhandslipdk@latimes.com');
insert into suggestion (Name, suggestName, message) values ('() { 0; }; touch /tmp/blns.shellshock1.fail;', '¸˛Ç◊ı˜Â¯˘¿', 'kmolloydl@biglobe.ne.jp');
insert into suggestion (Name, suggestName, message) values ('✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿', '田中さんにあげて下さい', 'bhawkingsdm@gravatar.com');
insert into suggestion (Name, suggestName, message) values ('åß∂ƒ©˙∆˚¬…æ', 'הָיְתָהtestالصفحات التّحول', 'vrialldn@tripod.com');
insert into suggestion (Name, suggestName, message) values ('!@#$%^&*()', '00˙Ɩ$-', 'pbarfielddo@utexas.edu');
insert into suggestion (Name, suggestName, message) values ('NIL', '-$1.00', 'ssilverthorndp@wp.com');
insert into suggestion (Name, suggestName, message) values ('1/0', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 'cstranddq@census.gov');
insert into suggestion (Name, suggestName, message) values ('''"''', '"''"''"''''''''"', 'tfinnimoredr@alibaba.com');
insert into suggestion (Name, suggestName, message) values ('''''', '-1', 'cgartands@netvibes.com');
insert into suggestion (Name, suggestName, message) values ('../../../../../../../../../../../etc/hosts', '../../../../../../../../../../../etc/hosts', 'frosenthaldt@fc2.com');
insert into suggestion (Name, suggestName, message) values ('''''', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 'celsterdu@printfriendly.com');
insert into suggestion (Name, suggestName, message) values ('1/0', '1;DROP TABLE users', 'aeratdv@clickbank.net');
